export const cnt: string;
export const city: string;
export const temperature: string;
export const description: string;
export const item: string;
export const tempnum: string;
export const image: string;
export const loading: string;
export const close: string;
